Repository ISISScientificComputing/autoreduce, pull requests merged in 2018-11, with the labels that each got.

#218 Add test coverage to get_last_run
  monitors/tests/test_icat_monitor.py
Labels: Monitors, Testing

#210 Add tests for icat client
  utils/clients/icat_client.py
  utils/clients/tests/test_icat_client.py
Labels: Maintenance, Testing

#208 Move serialisation to queue client
  monitors/end_of_run_monitor.py
  scripts/manual_submission_script/manual_submission.py
  scripts/manual_submission_script/tests/test_manual_submission.py
  utils/clients/queue_client.py
  utils/clients/tests/test_queue_client.py
Labels: Maintenance

#221 Increase test coverage in the monitors package
  .coveragerc
  .gitignore
  monitors/end_of_run_monitor.py
  monitors/health_check.py
  monitors/tests/test_end_of_run_monitors.py
  monitors/tests/test_health_check.py
Labels: Monitors, Testing

#232 Allow mysql password with newer version of mysql
  build/database/generate_database.py
Labels: Bug, Installation

#227 Add overview documentation
  .travis.yml
  build/README.md
  logs/README.md
  utils/clients/README.md
  utils/clients/client_class_diagram.PNG
  utils/clients/settings/README.md
  utils/project/README.md
Labels: Enhancement

#228 Resubmit missing runs from EoRM
  QueueProcessors/AutoreductionProcessor/autoreduction_processor.py
  monitors/health_check.py
  monitors/icat_monitor.py
  monitors/tests/test_health_check.py
  monitors/tests/test_icat_monitor.py
  utils/data_archive/tests/test_archive_explorer.py
Labels: High Priority, Monitors
