Repository ISISScientificComputing/autoreduce, pull requests merged in 2018-05, with the labels that each got.

#42 add setup py file
  .gitignore
  setup.py
Labels: Enhancement, Maintenance

#54 Improve pylint script
  QueueProcessors/AutoreductionProcessor/autoreduction_processor.py
  QueueProcessors/AutoreductionProcessor/autoreduction_processor_daemon.py
  QueueProcessors/AutoreductionProcessor/daemon.py
  QueueProcessors/AutoreductionProcessor/post_process_admin.py
  QueueProcessors/AutoreductionProcessor/timeout.py
  QueueProcessors/QueueProcessor/base.py
  QueueProcessors/QueueProcessor/daemon.py
  QueueProcessors/QueueProcessor/orm_mapping.py
  QueueProcessors/QueueProcessor/queue_processor.py
  QueueProcessors/QueueProcessor/queue_processor_daemon.py
  QueueProcessors/QueueProcessor/utils/instrument_utils.py
  QueueProcessors/QueueProcessor/utils/instrument_variable_utils.py
  QueueProcessors/QueueProcessor/utils/messaging_utils.py
  QueueProcessors/QueueProcessor/utils/reduction_run_utils.py
  QueueProcessors/QueueProcessor/utils/status_utils.py
  QueueProcessors/QueueProcessor/utils/variable_utils.py
  Scripts/Build/test/test_pylint.sh
Labels: Maintenance, Testing

#55 Refactor stomp and icat clients
  .travis.yml
  EndOfRunMonitor/ISISendOfRunMonitor.py
  EndOfRunMonitor/Stomp_Client.py
  EndOfRunMonitor/settings.py.template
  Scripts/Build/migrate_test_settings.sh
  Scripts/Build/test/test_activemq_connection.py
  utils/__init__.py
  utils/clients/__init__.py
  utils/clients/icat_client.py
  utils/clients/queue_client.py
  utils/clients/test_settings.py
  utils/clients/tests/__init__.py
  utils/clients/tests/test_clients.py
Labels: Maintenance, Monitors

#53 Add the data-archive creator to utils package
  utils/test_helpers/__init__.py
  utils/test_helpers/data_archive_creator.py
Labels: Testing

#61 37 Fix reduction run summary routing to use instrument name
  WebApp/autoreduce_webapp/autoreduce_webapp/urls.py
  WebApp/autoreduce_webapp/reduction_variables/views.py
  WebApp/autoreduce_webapp/reduction_viewer/views.py
  WebApp/autoreduce_webapp/templates/experiment_summary.html
  WebApp/autoreduce_webapp/templates/fail_queue.html
  WebApp/autoreduce_webapp/templates/run_confirmation.html
  WebApp/autoreduce_webapp/templates/run_queue.html
  WebApp/autoreduce_webapp/templates/run_summary.html
  WebApp/autoreduce_webapp/templates/snippets/instrument_status.html
  WebApp/autoreduce_webapp/templates/snippets/run_table.html
Labels: Enhancement, WebApp

#66 Add files for database data generation and testing
  .travis.yml
  Scripts/Build/generate_testing_database.sh
  Scripts/Build/migrate_test_settings.sh
  Scripts/Build/populate-reduction_viewer-db.sql
  Scripts/Build/test/test_db_generation.py
  Scripts/Build/travis-db-setup.sql
Labels: Enhancement, Testing

#65 Add generation script for apache_django_wsgi.conf
  .gitignore
  Scripts/Build/generate_apache_wsgi.py
  WebApp/autoreduce_webapp/apache/apache_django_wsgi.conf.template
Labels: Enhancement, WebApp

#69 Fix incorrect times being displayed on web app
  QueueProcessors/QueueProcessor/queue_processor.py
  QueueProcessors/QueueProcessor/utils/reduction_run_utils.py
Labels: Bug, WebApp

#63 Improve process for Webapp local build
  .travis.yml
  Scripts/ActiveMQTests/test_settings.py
  Scripts/Build/database/generate_testing_database.sh
  Scripts/Build/database/populate-reduction_viewer-db.sql
  Scripts/Build/database/travis-db-setup.sql
  Scripts/Build/generate_testing_database.sh
  Scripts/Build/install/activemq.bat
  Scripts/Build/install/activemq.sh
  Scripts/Build/install/icat.bat
  Scripts/Build/install/icat.sh
  Scripts/Build/migrate_test_settings.sh
  Scripts/Build/project/migrate_test_settings.sh
  Scripts/Build/test/test_db_generation.py
  Scripts/Build/tests/test_db_generation.py
  Scripts/Build/tests/test_pylint.sh
  Scripts/Build/tests/validate_icat.py
  WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py
  requirements.txt
  utils/clients/test_settings.py
Labels: Documentation, Enhancement, WebApp

#77 Improve QueueProcessor restart.sh
  QueueProcessors/restart.sh
Labels: Enhancement

#67 Upgrade travis to mysql version 5.7
  .travis.yml
  Scripts/Build/database/travis-db-setup.sql
Labels: Testing

#71 Add the database client to the utils package
  Scripts/Build/project/migrate_test_settings.sh
  utils/clients/database_client.py
  utils/clients/icat_client.py
  utils/clients/queue_client.py
  utils/clients/tests/test_clients.py
  utils/test_settings.py
Labels: Enhancement, Maintenance
