Repository ISISScientificComputing/autoreduce, pull requests merged in 2018-04, with the labels that each got.

#24 Remove unused monitor code
  QueueProcessors/AutoreductionProcessor/status_monitor.py
  QueueProcessors/AutoreductionProcessor/status_monitor_daemon.py
Labels: Maintenance

#26 Add testconfig.py.template
  .gitignore
  Scripts/ActiveMQTests/sendMessage.py
  Scripts/ActiveMQTests/settings.py.template
  Scripts/ActiveMQTests/stompActiveMQtest.py
  Scripts/ActiveMQTests/testconfig.py
Labels: High Priority

#20 Database build scripts and travis file
  .gitignore
  .travis.yml
  Scripts/Build/test/test_db_generation.py
  Scripts/Build/travis-db-setup.sql
  WebApp/autoreduce_webapp/autoreduce_webapp/icat_communication.py
  WebApp/autoreduce_webapp/autoreduce_webapp/queue_processor.py
  WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py
  WebApp/autoreduce_webapp/autoreduce_webapp/uows_client.py
  WebApp/autoreduce_webapp/autoreduce_webapp/view_utils.py
Labels: Testing

#23 Add activemq to travis setup
  .travis.yml
  Scripts/ActiveMQTests/reduce.py
  Scripts/ActiveMQTests/reduce_vars.py
  Scripts/ActiveMQTests/send_message.py
  Scripts/ActiveMQTests/test_settings.py
  Scripts/ActiveMQTests/test_stomp_activemq.py
  Scripts/ActiveMQTests/testconfig.py
  Scripts/Build/test/test_activemq_connection.py
Labels: Testing

#30 Remove unused ISIS_monitor_daemon
  EndOfRunMonitor/ISIS_monitor_daemon.py
  EndOfRunMonitor/isis_monitor_win_service.py
Labels: Maintenance

#32 Add re-design documentation to the developer-docs
  Documentation/developer-documents/AutoReduction-redesign-2018-04-18.pdf
  Documentation/developer-documents/EndOfRunMonitor-redesign-2018-04-18.pdf
Labels: Documentation

#40 Fix issues on the development nodes
  QueueProcessors/AutoreductionProcessor/autoreduction_logging_setup.py
  QueueProcessors/AutoreductionProcessor/autoreduction_processor.py
  QueueProcessors/AutoreductionProcessor/post_process_admin.py
  QueueProcessors/AutoreductionProcessor/settings.py.template
Labels: Bug, High Priority

#43 Simplfy travis script
  .travis.yml
  Scripts/Build/generate_testing_database.sh
  Scripts/Build/install_activemq.sh
  Scripts/Build/install_icat.sh
  Scripts/Build/migrate_test_settings.sh
  Scripts/Build/test/test_pylint.sh
  requirements.txt
Labels: Maintenance
