Repository ISISScientificComputing/autoreduce, pull requests merged in 2018-07, with the labels that each got.

#106 manual_submission.py now makes use of utils
  .travis.yml
  Scripts/ManualSubmissionScript/settings.py.template
  scripts/ActiveMQTests/__init__.py
  scripts/ActiveMQTests/reduce.py
  scripts/ActiveMQTests/reduce_vars.py
  scripts/ActiveMQTests/send_message.py
  scripts/ActiveMQTests/test_settings.py
  scripts/ActiveMQTests/test_stomp_activemq.py
  scripts/Build/database/generate_testing_database.sh
  scripts/Build/database/populate-reduction_viewer-db.sql
  scripts/Build/database/travis-db-setup.sql
  scripts/Build/generate_apache_wsgi.py
  scripts/Build/install/activemq.bat
  scripts/Build/install/activemq.sh
  scripts/Build/install/icat.bat
  scripts/Build/install/icat.sh
  scripts/Build/project/migrate_test_settings.sh
  scripts/Build/tests/test_db_generation.py
  scripts/Build/tests/test_pylint.sh
  scripts/Build/tests/validate_icat.py
  scripts/MySQLDumpScript/dumpDb.bat
  scripts/MySQLDumpScript/mysql_post_cycle.py
  scripts/NagiosChecks/__init__.py
  scripts/NagiosChecks/autoreduce_checkconsumers.py
  scripts/NagiosChecks/autoreduce_checklastrun.py
  scripts/NagiosChecks/autoreduce_checkqueuelength.py
  scripts/NagiosChecks/autoreduce_settings.py
  scripts/__init__.py
  scripts/isis-rhel.repo
  scripts/manual_submission_script/README.md
  scripts/manual_submission_script/__init__.py
  scripts/manual_submission_script/manual_submission.py
  scripts/manual_submission_script/requirments.txt
Labels: Enhancement, Maintenance

#110 Remove old and no longer required documentation
  Documentation/IIS/1_IIS.PNG
  Documentation/list_of_IIS_features.txt
  Documentation/meetings/2018-06-13.md
  Documentation/meetings/README.md
  Documentation/meetings/template.md
Labels: Documentation

#86 extend setup.py
  .gitattributes
  .gitignore
  .travis.yml
  WebApp/autoreduce_webapp/autoreduce_webapp/management/__init__.py
  WebApp/autoreduce_webapp/autoreduce_webapp/management/commands/__init__.py
  WebApp/autoreduce_webapp/autoreduce_webapp/management/commands/add_super.py
  build/__init__.py
  build/commands/__init__.py
  build/commands/database.py
  build/commands/help.py
  build/commands/installs.py
  build/commands/migrate_settings.py
  build/commands/start.py
  build/database/__init__.py
  build/database/generate_database.py
  build/database/populate_reduction_viewer.sql
  build/database/test_db_setup.sql
  build/generate_apache_wsgi.py
  build/install/7zip.bat
  build/install/__init__.py
  build/install/activemq.bat
  build/install/activemq.sh
  build/install/icat.bat
  build/install/icat.sh
  build/install/install_services.py
  build/install/mantid.sh
  build/test_settings.py
  build/tests/__init__.py
  build/tests/test_db_generation.py
  build/tests/test_pylint.sh
  build/tests/validate_installs.py
  build/utils/__init__.py
  build/utils/build_logger.py
  build/utils/common.py
  build/utils/process_runner.py
  setup.py
  utils/clients/database_client.py
  utils/clients/tests/test_clients.py
  utils/test_helpers/data_archive_creator.py
Labels: Enhancement, Testing

#118 Apply pylint project wide
  .pylintrc
  .travis.yml
  WebApp/autoreduce_webapp/tests/oldtest_autoreduce_webapp.py
  WebApp/autoreduce_webapp/tests/oldtest_reduction_variables.py
  WebApp/autoreduce_webapp/tests/oldtest_reduction_viewer.py
  build/install/activemq.sh
  build/install/icat.sh
  build/install/mantid.sh
  build/tests/test_pylint.sh
  scripts/Build/tests/test_pylint.sh
Labels: Maintenance, Testing

#122 Switch on coveralls
  .coveragerc
  .gitignore
  .travis.yml
  EndOfRunMonitor/isis_monitor_win_service.py
  QueueProcessors/AutoreductionProcessor/test_settings.py
  QueueProcessors/QueueProcessor/test_settings.py
  README.md
  WebApp/autoreduce_webapp/full_test.py
  WebApp/autoreduce_webapp/simple_stomp_test.py
  build/commands/migrate_settings.py
  build/tests/test_pylint.sh
  requirements.txt
Labels: Testing

#135 Ensure webapp is picked up in coverage
  .travis.yml
Labels: Testing

#133 Resolve pylint in utils
  build/tests/test_pylint.sh
  utils/clients/client_helper_functions.py
  utils/clients/database_client.py
  utils/clients/queue_client.py
  utils/clients/tests/test_clients.py
  utils/test_helpers/data_archive_creator.py
Labels: Maintenance
