Repository ISISScientificComputing/autoreduce, pull requests merged in 2018-10, with the labels that each got.

#195 Add git root function to find root directory
  setup.py
  utils/project/__init__.py
  utils/project/structure.py
  utils/project/tests/__init__.py
  utils/project/tests/test_structure.py
Labels: Enhancement

#202 Remove unused test files for syntax error
  WebApp/autoreduce_webapp/test_files/syntax_error/reduce.py
  WebApp/autoreduce_webapp/test_files/syntax_error/reduce_vars.py
  build/tests/test_pylint.sh
Labels: Maintenance

#209 ICAT Checker for EoRM
  monitors/end_of_run_monitor.py
  monitors/icat_monitor.py
  monitors/test_settings.py
  monitors/tests/test_icat_monitor.py
Labels: Monitors, Testing
