Repository ISISScientificComputing/autoreduce, pull requests merged in 2019-11, with the labels that each got.

#420 Python 3 - Build Steps
  .travis.yml
  WebApp/autoreduce_webapp/autoreduce_webapp/admin.py
  WebApp/autoreduce_webapp/autoreduce_webapp/backends.py
  WebApp/autoreduce_webapp/autoreduce_webapp/icat_cache.py
  WebApp/autoreduce_webapp/autoreduce_webapp/icat_communication.py
  WebApp/autoreduce_webapp/autoreduce_webapp/queue_processor.py
  WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/get_user_name.py
  WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/natural_time_difference.py
  WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/replace.py
  WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/view.py
  WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py
  WebApp/autoreduce_webapp/autoreduce_webapp/uows_client.py
  WebApp/autoreduce_webapp/autoreduce_webapp/urls.py
  WebApp/autoreduce_webapp/autoreduce_webapp/view_utils.py
  WebApp/autoreduce_webapp/autoreduce_webapp/views.py
  WebApp/autoreduce_webapp/reduction_variables/models.py
  WebApp/autoreduce_webapp/reduction_variables/utils.py
  WebApp/autoreduce_webapp/reduction_viewer/models.py
Labels: 👤 Developer Requirement, 🔑 Database, 🔑 Internal

#421 Python3 - Unit tests
  WebApp/autoreduce_webapp/tests/test_input_processing.py
  monitors/run_detection.py
  monitors/tests/test_run_detection.py
  paths/tests/test_collections.py
  paths/tests/test_path.py
  queue_processors/autoreduction_processor/post_process_admin.py
  queue_processors/daemon.py
  queue_processors/queue_processor/queueproc_utils/instrument_variable_utils.py
  queue_processors/queue_processor/test_settings.py
  scripts/database_management/tests/test_cycle_database_reset.py
  scripts/manual_operations/manual_remove.py
  scripts/manual_operations/tests/test_manual_remove.py
  utils/clients/settings/tests/test_client_settings.py
  utils/clients/settings/tests/test_client_settings_factory.py
  utils/clients/tests/test_abstract_client.py
  utils/clients/tests/test_icat_client.py
  utils/data_archive/data_archive_creator.py
  utils/data_archive/tests/test_data_archive_creator.py
  utils/data_archive/tests/test_file_filter.py
Labels: 👤 Developer Requirement, 🔑 Internal, 🔑 Testing

#422 Python 3 - system tests
  WebApp/autoreduce_webapp/autoreduce_webapp/daemon.py
  queue_processors/autoreduction_processor/post_process_admin.py
  queue_processors/daemon.py
  queue_processors/queue_processor/base.py
  scripts/manual_operations/manual_remove.py
  systemtests/test_end_to_end.py
Labels: 👤 Developer Requirement, 🔑 Internal, 🔑 Testing

#424 Python 3 - Pylint
  build/commands/database.py
  build/commands/help.py
  build/commands/installs.py
  build/commands/start.py
  build/database/generate_database.py
  build/database/tests/test_generate_database.py
  build/tests/test_db_generation.py
  build/tests/validate_installs.py
  build/utils/build_logger.py
  docker_reduction/mantid/operations.py
  docker_reduction/mount.py
  monitors/run_detection.py
  monitors/tests/test_run_detection.py
  queue_processors/autoreduction_processor/autoreduction_processor.py
  queue_processors/autoreduction_processor/post_process_admin.py
  queue_processors/autoreduction_processor/tests/test_post_process_admin.py
  queue_processors/autoreduction_processor/timeout.py
  queue_processors/daemon.py
  queue_processors/queue_processor/queue_processor.py
  queue_processors/queue_processor/queueproc_utils/instrument_utils.py
  queue_processors/queue_processor/queueproc_utils/instrument_variable_utils.py
  queue_processors/queue_processor/queueproc_utils/messaging_utils.py
  queue_processors/queue_processor/queueproc_utils/reduction_run_utils.py
  queue_processors/queue_processor/queueproc_utils/status_utils.py
  queue_processors/queue_processor/queueproc_utils/variable_utils.py
  scripts/database_management/reset_database_post_cycle.py
  scripts/manual_operations/manual_remove.py
  scripts/manual_operations/tests/test_manual_submission.py
  systemtests/test_end_to_end.py
  utils/clients/database_client.py
  utils/clients/settings/client_settings.py
  utils/clients/settings/client_settings_factory.py
  utils/data_archive/archive_explorer.py
  utils/data_archive/data_archive_creator.py
  utils/data_archive/tests/test_data_archive_creator.py
  utils/project/structure.py
Labels: 👤 Developer Requirement, 🔑 Internal

#430 py3 manual testing webapp
  WebApp/autoreduce_webapp/autoreduce_webapp/icat_cache.py
  WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/get_user_name.py
  WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/replace.py
  WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/view.py
  WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py
  WebApp/autoreduce_webapp/autoreduce_webapp/view_utils.py
  WebApp/autoreduce_webapp/reduction_variables/utils.py
  WebApp/autoreduce_webapp/reduction_variables/views.py
  WebApp/autoreduce_webapp/reduction_viewer/views.py
  WebApp/autoreduce_webapp/templates/experiment_summary.html
  WebApp/autoreduce_webapp/templates/fail_queue.html
  WebApp/autoreduce_webapp/templates/instrument_summary.html
  WebApp/autoreduce_webapp/templates/instrument_variables.html
  WebApp/autoreduce_webapp/templates/overview.html
  WebApp/autoreduce_webapp/templates/run_summary.html
  WebApp/autoreduce_webapp/templates/snippets/instrument_status.html
  WebApp/autoreduce_webapp/templates/snippets/run_table.html
  WebApp/autoreduce_webapp/templates/snippets/variables.html
  build/install/icat.bat
  build/install/icat.sh
Labels: 👤 Developer Requirement, 🔑 Internal, 🔑 WebApp

#427 Cycle Web Scraper Script
  Documentation/docs_for_main_readme/Autoreduction_main_components.png
  Documentation/docs_for_main_readme/README.md
  README.md
  WebApp/README.md
  WebApp/autoreduce_webapp/reduction_viewer/views.py
  queue_processors/README.md
  requirements.txt
  scripts/system_performance/__init__.py
  scripts/system_performance/cycle_dates.csv
  scripts/system_performance/cycle_webscraper.py
  scripts/system_performance/tests/__init__.py
  scripts/system_performance/tests/test_cycle_webscraper.py
Labels: 👤 Developer Requirement, 🔑 Internal
