Repository ISISScientificComputing/autoreduce, pull requests merged in 2019-02, with the labels that each got.

#245 Remove resubmit of first run from EoRM health check
  monitors/health_check.py
  monitors/tests/test_health_check.py
Labels: Bug, Monitors

#238 CEPH link in webapp
  WebApp/autoreduce_webapp/reduction_viewer/views.py
  WebApp/autoreduce_webapp/templates/help.html
  WebApp/autoreduce_webapp/templates/run_summary.html
  build/database/populate_reduction_viewer.sql
Labels: :bust_in_silhouette: User requirement, :key: WebApp

#206 Add logging in expected location and standardise format
  QueueProcessors/QueueProcessor/test_settings.py
  monitors/end_of_run_monitor.py
  scripts/activemq_tests/send_message.py
  scripts/activemq_tests/test_settings.py
  scripts/activemq_tests/test_stomp_activemq.py
  utils/clients/database_client.py
  utils/clients/icat_client.py
  utils/clients/queue_client.py
  utils/project/static_content.py
  utils/project/structure.py
  utils/project/tests/test_structure.py
Labels: :bust_in_silhouette: Developer Requirement, :key: Internal

#267 DataArchiveCreator reduce.py and reduce_vars.py
  utils/data_archive/archive_explorer.py
  utils/data_archive/data_archive_creator.py
  utils/data_archive/tests/test_archive_explorer.py
  utils/data_archive/tests/test_data_archive_creator.py
Labels: :bust_in_silhouette: Developer Requirement, :key: Internal, :key: Testing

#279 Change for the user office update
  WebApp/autoreduce_webapp/autoreduce_webapp/uows_client.py
Labels: :bust_in_silhouette: Developer Requirement, :clock1: High Priority, :key: WebApp

#275 Order database runs by run number
  monitors/health_check.py
Labels: :bust_in_silhouette: Developer Requirement, :exclamation: Bug, :key: Internal

#269 Added basic documentation to remaining areas
  QueueProcessors/AutoreductionProcessor/README.md
  QueueProcessors/QueueProcessor/README.md
  QueueProcessors/README.md
  monitors/README.md
  scripts/NagiosChecks/README.md
  scripts/README.md
  scripts/database_management/README.md
  scripts/database_management/__init__.py
  scripts/database_management/reset_database_post_cycle.py
  scripts/database_management/tests/__init__.py
  scripts/database_management/tests/test_cycle_database_reset.py
  scripts/manual_submission_script/README.md
  utils/README.md
Labels: :bust_in_silhouette: Developer Requirement, :clock1: Low priority, :key: Documentation

#283 Fix test failure introduced due to resolveing merge conflict
  monitors/tests/test_health_check.py
Labels: :bust_in_silhouette: Developer Requirement, :clock1: High Priority, :key: Testing
