Repository ISISScientificComputing/autoreduce, pull requests merged in 2020-04, with the labels that each got.

#510 Basic AMQ message class
  .travis.yml
  message/__init__.py
  message/job.py
  message/tests/__init__.py
  message/tests/test_job.py
  setup.py
Labels: 👤 Developer Requirement, 🔑 Queues

#518 Remove use of raw stomp in autoreduction_processor.py
  queue_processors/autoreduction_processor/autoreduction_processor.py
  queue_processors/autoreduction_processor/tests/test_autoreduction_processor.py
Labels: 🔑 Queues

#516 Improve docstrings in scripts / mantid
  scripts/mantid/tests/test_properties.py
Labels: 🔑 Documentation, 🔑 Testing

#521 Add tests for usages of QueueClient
  queue_processors/queue_processor/queueproc_utils/tests/test_messaging_utils.py
  queue_processors/queue_processor/tests/__init__.py
  queue_processors/queue_processor/tests/test_queue_processor.py
Labels: 🔑 Queues, 🔑 Testing

#509 Implement BootstrapTour to WebApp homepage
  WebApp/autoreduce_webapp/static/css/vendor/bootstrap-tour.min.css
  WebApp/autoreduce_webapp/static/javascript/create_tour.js
  WebApp/autoreduce_webapp/static/javascript/tours/navbar-tour.js
  WebApp/autoreduce_webapp/static/javascript/tours/overview-tour.js
  WebApp/autoreduce_webapp/static/javascript/vendor/bootstrap-tour.min.js
  WebApp/autoreduce_webapp/templates/navbar.html
  WebApp/autoreduce_webapp/templates/overview.html
Labels: 🔄 In progress, 🔑 Documentation, 🔑 WebApp
