Repository ISISScientificComputing/autoreduce, pull requests merged in 2020-10, with the labels that each got.

#781 764 fix output structure
  paths/isis/isis_reduction_path_manager.py
  queue_processors/autoreduction_processor/post_process_admin.py
  queue_processors/autoreduction_processor/test_settings.py
  queue_processors/autoreduction_processor/tests/test_post_process_admin.py
Labels: :exclamation: Release requirement

#793 Fixes runs not displaying due to any error in plot retrieving code
  WebApp/autoreduce_webapp/reduction_viewer/views.py
  WebApp/autoreduce_webapp/templates/run_summary.html
  plotting/plot_handler.py
Labels: :exclamation: Release requirement

#836 Can't submit jobs after database cleared
  model/database/access.py
Labels: ❗️ Bug

#849 Catch the base exception
  WebApp/autoreduce_webapp/reduction_viewer/utils.py
Labels: :exclamation: Backport-PR

#851 Allow blank software
  WebApp/autoreduce_webapp/reduction_viewer/models.py
Labels: :exclamation: Backport-PR

#861 Tweak WebApp tours
  WebApp/autoreduce_webapp/static/javascript/tours/instrument_summary_tour.js
  WebApp/autoreduce_webapp/static/javascript/tours/navbar_tour.js
  WebApp/autoreduce_webapp/static/javascript/tours/run_summary_tour.js
  WebApp/autoreduce_webapp/templates/instrument_summary.html
  WebApp/autoreduce_webapp/templates/run_summary.html
Labels: :key: WebApp

#792 Accommodate SOAP/WSDL URL migration
  WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py
  WebApp/autoreduce_webapp/autoreduce_webapp/uows_client.py
Labels: :exclamation: Backport-PR, :exclamation: Release requirement, :key: WebApp

#854 Cleanup run summary for skipped runs
  WebApp/autoreduce_webapp/reduction_viewer/views.py
  WebApp/autoreduce_webapp/templates/run_summary.html
Labels: :exclamation: Backport-PR

#872 Implements fix for correctly updating the Python dicts
  queue_processors/autoreduction_processor/post_process_admin.py
Labels: :clock1: High Priority, :exclamation: Backport-PR, ❗️ Bug
